import { CarrierConfig } from "./types";

export const americanAmicable: CarrierConfig = {
  id: "american-amicable",
  name: "American Amicable",
  portalUrl: "https://www.americanamicable.com/v4/login.html",
  stateExclusions: ["NY", "MT", "MN", "NH", "ME"],
  productStateExclusions: {},
  tobaccoPolicy: {
    lookbackMonths: 12,
    preferredLookbackMonths: 36,
    cigarException: true,
    vapingIsTobacco: true,
  },
  knockoutConditions: [
    "alzheimers", "dementia", "als", "huntingtons", "hiv",
    "organ_transplant", "dialysis", "terminal_illness",
    "wheelchair", "nursing_home", "adl_assistance", "oxygen_use",
    "chf", "cancer_active", "cancer_multiple", "sickle_cell",
    "amputation_disease", "pending_treatment",
    "diabetes_complications", "kidney_disease",
  ],
  underwritingTiers: [
    {
      id: "preferred-nt",
      name: "Preferred Non-Tobacco",
      triggerConditions: [],
      isGraded: false,
      premiumMultiplier: 0.7,
    },
    {
      id: "standard-nt",
      name: "Standard Non-Tobacco",
      triggerConditions: ["hypertension", "high_cholesterol", "diabetes_type2", "obesity"],
      isGraded: false,
      premiumMultiplier: 1.0,
    },
    {
      id: "standard-tobacco",
      name: "Standard Tobacco",
      triggerConditions: [],
      isGraded: false,
      premiumMultiplier: 1.8,
    },
    {
      id: "immediate",
      name: "Immediate Benefit (Final Expense)",
      triggerConditions: [],
      isGraded: false,
      premiumMultiplier: 1.0,
    },
    {
      id: "graded",
      name: "Graded Benefit",
      triggerConditions: [
        "heart_attack", "stroke", "angina", "aneurysm", "heart_surgery",
        "cancer_history", "copd", "parkinsons", "ms", "cerebral_palsy",
        "muscular_dystrophy", "seizures", "liver_disease",
      ],
      lookbackMonths: 36,
      isGraded: true,
      premiumMultiplier: 1.5,
    },
    {
      id: "rop",
      name: "Return of Premium",
      triggerConditions: [
        "angina", "stroke", "tia", "cardiomyopathy", "lupus",
        "hepatitis_c", "copd", "alcohol_abuse", "drug_abuse",
      ],
      lookbackMonths: 24,
      isGraded: true,
      premiumMultiplier: 1.8,
    },
  ],
  products: [
    {
      id: "aa-term-made-simple",
      name: "Term Made Simple",
      type: "term",
      issueAgeMin: 18,
      issueAgeMax: 75,
      faceAmountMin: 50000,
      faceAmountMax: 500000,
      termLengths: [10, 15, 20, 30],
      underwritingType: "simplified",
    },
    {
      id: "aa-senior-choice",
      name: "Senior Choice Whole Life",
      type: "final_expense",
      issueAgeMin: 50,
      issueAgeMax: 85,
      faceAmountMin: 2500,
      faceAmountMax: 35000,
      faceAmountMaxByAge: [
        { minAge: 50, maxAge: 75, max: 35000 },
        { minAge: 76, maxAge: 85, max: 20000 },
      ],
      underwritingType: "simplified",
    },
    {
      id: "aa-intelligent-choice-iul",
      name: "Intelligent Choice IUL",
      type: "iul",
      issueAgeMin: 18,
      issueAgeMax: 75,
      faceAmountMin: 25000,
      faceAmountMax: 500000,
      underwritingType: "simplified",
    },
    {
      id: "aa-easy-ul",
      name: "Easy UL",
      type: "whole_life",
      issueAgeMin: 0,
      issueAgeMax: 85,
      faceAmountMin: 10000,
      faceAmountMax: 500000,
      underwritingType: "simplified",
    },
  ],
};
