import { CarrierConfig } from "./types";

export const americo: CarrierConfig = {
  id: "americo",
  name: "Americo",
  portalUrl: "https://www.americo.com/agents/",
  stateExclusions: ["NY"],
  productStateExclusions: {
    "eagle-premier": ["CA", "CT", "NY", "PA", "VT"],
    "ultra-protector-1": ["MS", "NY", "VT"],
    "ultra-protector-3": ["AR", "MA", "MN", "MS", "MT", "NY", "PA", "VT", "WA"],
  },
  tobaccoPolicy: {
    lookbackMonths: 24,
    cigarException: true,
    vapingIsTobacco: true,
  },
  knockoutConditions: [
    "organ_transplant", "ms", "als", "lupus", "alzheimers", "dementia",
    "huntingtons", "parkinsons", "amputation_disease", "liver_disease",
    "wheelchair", "nursing_home", "hospice", "oxygen_use", "adl_assistance",
    "pending_treatment", "hiv", "dialysis", "terminal_illness",
    "diabetes_complications", "cancer_active", "cancer_multiple",
    "sickle_cell", "cystic_fibrosis", "muscular_dystrophy",
    "pulmonary_fibrosis", "drug_abuse",
  ],
  underwritingTiers: [
    {
      id: "standard-non-nicotine",
      name: "Standard Non-Nicotine",
      triggerConditions: [],
      isGraded: false,
      premiumMultiplier: 1.0,
    },
    {
      id: "standard-nicotine",
      name: "Standard Nicotine",
      triggerConditions: [],
      isGraded: false,
      premiumMultiplier: 1.8,
    },
    {
      id: "eagle-select-1",
      name: "Eagle Select 1 (Final Expense)",
      triggerConditions: [],
      isGraded: false,
      premiumMultiplier: 1.0,
    },
    {
      id: "eagle-select-2",
      name: "Eagle Select 2 (Final Expense)",
      triggerConditions: ["diabetes_type2", "heart_attack", "stroke", "tia"],
      lookbackMonths: 24,
      isGraded: false,
      premiumMultiplier: 1.3,
    },
    {
      id: "eagle-select-3",
      name: "Eagle Select 3 (Guaranteed Issue)",
      triggerConditions: [],
      isGraded: true,
      premiumMultiplier: 1.8,
    },
  ],
  products: [
    {
      id: "americo-term-100",
      name: "Term 100",
      type: "term",
      issueAgeMin: 20,
      issueAgeMax: 75,
      faceAmountMin: 25000,
      faceAmountMax: 450000,
      termLengths: [15, 20, 25, 30],
      underwritingType: "simplified",
    },
    {
      id: "americo-iul",
      name: "Instant Decision IUL",
      type: "iul",
      issueAgeMin: 18,
      issueAgeMax: 65,
      faceAmountMin: 50000,
      faceAmountMax: 450000,
      underwritingType: "simplified",
    },
    {
      id: "americo-eagle-select",
      name: "Eagle Select Final Expense",
      type: "final_expense",
      issueAgeMin: 40,
      issueAgeMax: 85,
      faceAmountMin: 5000,
      faceAmountMax: 40000,
      underwritingType: "simplified",
    },
    {
      id: "americo-advantage-wl",
      name: "AdvantageWL Whole Life",
      type: "whole_life",
      issueAgeMin: 18,
      issueAgeMax: 75,
      faceAmountMin: 25000,
      faceAmountMax: 100000,
      underwritingType: "simplified",
    },
  ],
};
