import { CarrierConfig } from "./types";

export const corebridge: CarrierConfig = {
  id: "corebridge",
  name: "Corebridge Financial",
  portalUrl: "https://www.corebridgefinancial.com/financial-professional",
  stateExclusions: [],
  productStateExclusions: {},
  tobaccoPolicy: {
    lookbackMonths: 12,
    cigarException: true,
    vapingIsTobacco: true,
  },
  knockoutConditions: [
    "alzheimers", "dementia", "als", "huntingtons", "hiv",
    "organ_transplant", "dialysis", "terminal_illness",
    "wheelchair", "nursing_home", "adl_assistance", "oxygen_use",
    "cancer_active", "cancer_multiple", "sickle_cell",
    "cystic_fibrosis", "muscular_dystrophy", "pulmonary_fibrosis",
    "amputation_disease", "pending_treatment",
  ],
  underwritingTiers: [
    {
      id: "preferred-plus-nt",
      name: "Preferred Plus Non-Tobacco",
      triggerConditions: [],
      isGraded: false,
      premiumMultiplier: 0.7,
    },
    {
      id: "preferred-nt",
      name: "Preferred Non-Tobacco",
      triggerConditions: ["hypertension", "high_cholesterol", "sleep_apnea"],
      isGraded: false,
      premiumMultiplier: 0.85,
    },
    {
      id: "standard-nt",
      name: "Standard Non-Tobacco",
      triggerConditions: ["diabetes_type2", "depression", "afib", "asthma", "obesity"],
      isGraded: false,
      premiumMultiplier: 1.0,
    },
    {
      id: "preferred-tobacco",
      name: "Preferred Tobacco",
      triggerConditions: [],
      isGraded: false,
      premiumMultiplier: 1.6,
    },
    {
      id: "standard-tobacco",
      name: "Standard Tobacco",
      triggerConditions: [],
      isGraded: false,
      premiumMultiplier: 2.0,
    },
    {
      id: "substandard",
      name: "Substandard (Table Rated)",
      triggerConditions: ["heart_attack", "stroke", "cancer_history", "copd", "kidney_disease", "liver_disease"],
      isGraded: false,
      premiumMultiplier: 2.5,
    },
    {
      id: "simplinow-max",
      name: "SimpliNow Legacy Max (Day-1 FE)",
      triggerConditions: [],
      isGraded: false,
      premiumMultiplier: 1.2,
    },
    {
      id: "simplinow-graded",
      name: "SimpliNow Legacy (Graded FE)",
      triggerConditions: ["parkinsons", "ms", "bipolar", "lupus", "schizophrenia", "alcohol_abuse", "drug_abuse"],
      isGraded: true,
      premiumMultiplier: 1.6,
    },
  ],
  products: [
    {
      id: "corebridge-select-a-term",
      name: "Select-a-Term",
      type: "term",
      issueAgeMin: 20,
      issueAgeMax: 80,
      faceAmountMin: 100000,
      faceAmountMax: 5000000,
      termLengths: [10, 15, 20, 25, 30],
      underwritingType: "fully_underwritten",
    },
    {
      id: "corebridge-max-accumulator-iul",
      name: "Max Accumulator+ IUL",
      type: "iul",
      issueAgeMin: 18,
      issueAgeMax: 80,
      faceAmountMin: 50000,
      faceAmountMax: 5000000,
      underwritingType: "fully_underwritten",
    },
    {
      id: "corebridge-simplinow-max",
      name: "SimpliNow Legacy Max",
      type: "final_expense",
      issueAgeMin: 50,
      issueAgeMax: 80,
      faceAmountMin: 5000,
      faceAmountMax: 35000,
      underwritingType: "simplified",
    },
    {
      id: "corebridge-gi-wl",
      name: "Guaranteed Issue Whole Life",
      type: "final_expense",
      issueAgeMin: 50,
      issueAgeMax: 80,
      faceAmountMin: 5000,
      faceAmountMax: 25000,
      underwritingType: "guaranteed",
      gradedBenefit: {
        years: [
          { year: 1, benefitPct: 0 },
          { year: 2, benefitPct: 0 },
          { year: 3, benefitPct: 100 },
        ],
        accidentalDeathFullBenefit: true,
        returnOfPremiumPct: 110,
      },
    },
  ],
};
