import { CarrierConfig } from "./types";

export const mutualOfOmaha: CarrierConfig = {
  id: "mutual-of-omaha",
  name: "Mutual of Omaha",
  portalUrl: "https://www.mutualofomaha.com/broker",
  stateExclusions: [],
  productStateExclusions: {
    "moo-living-promise": ["NY"],
  },
  tobaccoPolicy: {
    lookbackMonths: 12,
    preferredLookbackMonths: 36,
    cigarException: true,
    vapingIsTobacco: true,
  },
  knockoutConditions: [
    "alzheimers", "dementia", "als", "huntingtons", "hiv",
    "organ_transplant", "dialysis", "terminal_illness",
    "wheelchair", "nursing_home", "adl_assistance", "oxygen_use",
    "chf", "cancer_active", "cancer_multiple", "sickle_cell",
    "cystic_fibrosis", "amputation_disease", "pending_treatment",
    "pulmonary_fibrosis", "drug_abuse",
  ],
  underwritingTiers: [
    {
      id: "preferred-best-nt",
      name: "Preferred Best Non-Tobacco",
      triggerConditions: [],
      isGraded: false,
      premiumMultiplier: 0.6,
    },
    {
      id: "preferred-nt",
      name: "Preferred Non-Tobacco",
      triggerConditions: ["high_cholesterol"],
      isGraded: false,
      premiumMultiplier: 0.75,
    },
    {
      id: "standard-plus-nt",
      name: "Standard Plus Non-Tobacco",
      triggerConditions: ["hypertension", "sleep_apnea", "obesity"],
      isGraded: false,
      premiumMultiplier: 0.9,
    },
    {
      id: "standard-nt",
      name: "Standard Non-Tobacco",
      triggerConditions: [
        "diabetes_type2", "copd", "depression", "bipolar", "asthma",
        "heart_attack", "stroke", "afib", "seizures", "parkinsons", "ms",
        "alcohol_abuse", "dui", "cancer_history", "liver_disease", "hepatitis_c",
      ],
      isGraded: false,
      premiumMultiplier: 1.0,
    },
    {
      id: "preferred-tobacco",
      name: "Preferred Tobacco",
      triggerConditions: [],
      isGraded: false,
      premiumMultiplier: 1.6,
    },
    {
      id: "standard-tobacco",
      name: "Standard Tobacco",
      triggerConditions: [],
      isGraded: false,
      premiumMultiplier: 2.0,
    },
    {
      id: "substandard",
      name: "Substandard (Table Rated)",
      triggerConditions: ["heart_surgery", "aneurysm", "cardiomyopathy", "lupus", "schizophrenia"],
      isGraded: false,
      premiumMultiplier: 2.5,
    },
  ],
  products: [
    {
      id: "moo-term-express",
      name: "Term Life Express",
      type: "term",
      issueAgeMin: 18,
      issueAgeMax: 65,
      faceAmountMin: 25000,
      faceAmountMax: 300000,
      termLengths: [10, 15, 20, 30],
      underwritingType: "simplified",
    },
    {
      id: "moo-living-promise",
      name: "Living Promise (GI Whole Life)",
      type: "final_expense",
      issueAgeMin: 45,
      issueAgeMax: 85,
      faceAmountMin: 2000,
      faceAmountMax: 25000,
      underwritingType: "guaranteed",
      gradedBenefit: {
        years: [
          { year: 1, benefitPct: 0 },
          { year: 2, benefitPct: 0 },
          { year: 3, benefitPct: 100 },
        ],
        accidentalDeathFullBenefit: true,
        returnOfPremiumPct: 110,
      },
    },
    {
      id: "moo-iul",
      name: "Life Protection Advantage IUL",
      type: "iul",
      issueAgeMin: 0,
      issueAgeMax: 75,
      faceAmountMin: 25000,
      faceAmountMax: 1000000,
      underwritingType: "fully_underwritten",
    },
    {
      id: "moo-whole-life",
      name: "Whole Life",
      type: "whole_life",
      issueAgeMin: 18,
      issueAgeMax: 80,
      faceAmountMin: 25000,
      faceAmountMax: 500000,
      underwritingType: "fully_underwritten",
    },
  ],
};
