import { CarrierConfig } from "./types";

export const transamerica: CarrierConfig = {
  id: "transamerica",
  name: "Transamerica",
  portalUrl: "https://www.transamerica.com/agent",
  stateExclusions: [],
  productStateExclusions: {
    "transamerica-trendsetter": ["NY"],
    "transamerica-lifetime-wl": ["NY"],
    "transamerica-ffiul": ["NY"],
    "transamerica-fe-express": ["CA", "NY", "PA"],
    "transamerica-easy-solution": ["CA", "NY", "PA"],
  },
  tobaccoPolicy: {
    lookbackMonths: 12,
    preferredLookbackMonths: 36,
    cigarException: true,
    vapingIsTobacco: true,
  },
  knockoutConditions: [
    "alzheimers", "dementia", "als", "huntingtons", "hiv",
    "organ_transplant", "dialysis", "terminal_illness",
    "wheelchair", "nursing_home", "adl_assistance", "oxygen_use",
    "cancer_active", "cancer_multiple", "sickle_cell",
    "cystic_fibrosis", "cerebral_palsy", "amputation_disease",
    "pending_treatment", "pulmonary_fibrosis", "diabetes_complications",
  ],
  underwritingTiers: [
    {
      id: "preferred-plus-ns",
      name: "Preferred Plus Nonsmoker",
      triggerConditions: [],
      isGraded: false,
      premiumMultiplier: 0.65,
    },
    {
      id: "preferred-ns",
      name: "Preferred Nonsmoker",
      triggerConditions: ["hypertension", "high_cholesterol"],
      isGraded: false,
      premiumMultiplier: 0.8,
    },
    {
      id: "standard-plus-ns",
      name: "Standard Plus Nonsmoker",
      triggerConditions: ["sleep_apnea", "asthma", "obesity"],
      isGraded: false,
      premiumMultiplier: 0.9,
    },
    {
      id: "standard-ns",
      name: "Standard Nonsmoker",
      triggerConditions: [
        "diabetes_type2", "copd", "parkinsons", "ms", "heart_attack",
        "stroke", "angina", "afib", "depression", "bipolar",
      ],
      isGraded: false,
      premiumMultiplier: 1.0,
    },
    {
      id: "preferred-smoker",
      name: "Preferred Smoker",
      triggerConditions: [],
      isGraded: false,
      premiumMultiplier: 1.5,
    },
    {
      id: "standard-smoker",
      name: "Standard Smoker",
      triggerConditions: [],
      isGraded: false,
      premiumMultiplier: 2.0,
    },
    {
      id: "substandard",
      name: "Substandard (Table Rated)",
      triggerConditions: ["cancer_history", "kidney_disease", "liver_disease", "alcohol_abuse", "drug_abuse"],
      isGraded: false,
      premiumMultiplier: 2.5,
    },
  ],
  products: [
    {
      id: "transamerica-trendsetter",
      name: "Trendsetter Super Term",
      type: "term",
      issueAgeMin: 18,
      issueAgeMax: 80,
      issueAgeMaxSmoker: 80,
      faceAmountMin: 25000,
      faceAmountMax: 10000000,
      termLengths: [10, 15, 20, 25, 30],
      underwritingType: "fully_underwritten",
    },
    {
      id: "transamerica-lifetime-wl",
      name: "Lifetime Whole Life",
      type: "whole_life",
      issueAgeMin: 0,
      issueAgeMax: 80,
      faceAmountMin: 25000,
      faceAmountMax: 2000000,
      underwritingType: "fully_underwritten",
    },
    {
      id: "transamerica-ffiul",
      name: "Financial Foundation IUL",
      type: "iul",
      issueAgeMin: 0,
      issueAgeMax: 85,
      faceAmountMin: 25000,
      faceAmountMax: 2000000,
      underwritingType: "fully_underwritten",
    },
    {
      id: "transamerica-fe-express",
      name: "FE Express Solution",
      type: "final_expense",
      issueAgeMin: 18,
      issueAgeMax: 85,
      faceAmountMin: 5000,
      faceAmountMax: 50000,
      faceAmountMaxByAge: [
        { minAge: 18, maxAge: 75, max: 50000 },
        { minAge: 76, maxAge: 85, max: 25000 },
      ],
      underwritingType: "simplified",
    },
    {
      id: "transamerica-easy-solution",
      name: "Easy Solution (Graded)",
      type: "final_expense",
      issueAgeMin: 18,
      issueAgeMax: 80,
      faceAmountMin: 1000,
      faceAmountMax: 25000,
      underwritingType: "simplified",
      gradedBenefit: {
        years: [
          { year: 1, benefitPct: 30 },
          { year: 2, benefitPct: 60 },
          { year: 3, benefitPct: 100 },
        ],
        accidentalDeathFullBenefit: true,
      },
    },
  ],
};
