import { ConditionCategory } from "./categories";
import { ConditionEffect } from "@/lib/carriers/types";

export interface ConditionImpact {
  effect: ConditionEffect;
  lookbackMonths?: number;
  notes?: string;
}

export interface Condition {
  id: string;
  name: string;
  aliases: string[];
  category: ConditionCategory;
  severityWeight: number;
  carrierImpact: Record<string, ConditionImpact>;
}

export const masterConditionList: Condition[] = [
  // === CARDIAC ===
  {
    id: "chf",
    name: "Congestive Heart Failure",
    aliases: ["CHF", "heart failure", "weak heart", "cardiac failure"],
    category: "cardiac",
    severityWeight: 14,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout", notes: "CHF with defibrillator is knockout; without may be graded" },
      transamerica: { effect: "graded", lookbackMonths: 24, notes: "Graded if within 2 years; standard if older" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },
  {
    id: "heart_attack",
    name: "Heart Attack",
    aliases: ["myocardial infarction", "MI", "cardiac arrest", "coronary event"],
    category: "cardiac",
    severityWeight: 12,
    carrierImpact: {
      americo: { effect: "standard_only", lookbackMonths: 24 },
      corebridge: { effect: "rated", lookbackMonths: 24 },
      transamerica: { effect: "standard_only", lookbackMonths: 24, notes: "Graded if within 2 years" },
      aetna: { effect: "modified", lookbackMonths: 12, notes: "Standard if 1-2 years; Preferred if 2+ years" },
      "american-amicable": { effect: "graded", lookbackMonths: 36, notes: "Immediate if 3+ years ago" },
      "mutual-of-omaha": { effect: "rated", lookbackMonths: 12 },
    },
  },
  {
    id: "angina",
    name: "Angina",
    aliases: ["chest pain", "angina pectoris"],
    category: "cardiac",
    severityWeight: 10,
    carrierImpact: {
      americo: { effect: "standard_only", lookbackMonths: 24 },
      corebridge: { effect: "rated", lookbackMonths: 24 },
      transamerica: { effect: "standard_only", lookbackMonths: 24 },
      aetna: { effect: "modified", lookbackMonths: 12, notes: "Standard if 1-2 yrs; Preferred if 2+" },
      "american-amicable": { effect: "graded", lookbackMonths: 36 },
      "mutual-of-omaha": { effect: "rated", lookbackMonths: 12 },
    },
  },
  {
    id: "stroke",
    name: "Stroke",
    aliases: ["CVA", "cerebrovascular accident", "brain attack"],
    category: "cardiac",
    severityWeight: 12,
    carrierImpact: {
      americo: { effect: "standard_only", lookbackMonths: 24 },
      corebridge: { effect: "rated", lookbackMonths: 24 },
      transamerica: { effect: "standard_only", lookbackMonths: 24 },
      aetna: { effect: "modified", lookbackMonths: 12, notes: "Standard if 1-2 yrs" },
      "american-amicable": { effect: "graded", lookbackMonths: 36 },
      "mutual-of-omaha": { effect: "rated", lookbackMonths: 12 },
    },
  },
  {
    id: "tia",
    name: "TIA (Mini-Stroke)",
    aliases: ["transient ischemic attack", "mini stroke", "mini-stroke"],
    category: "cardiac",
    severityWeight: 8,
    carrierImpact: {
      americo: { effect: "standard_only", lookbackMonths: 24 },
      corebridge: { effect: "rated", lookbackMonths: 24 },
      transamerica: { effect: "standard_only", lookbackMonths: 24 },
      aetna: { effect: "modified", lookbackMonths: 12 },
      "american-amicable": { effect: "graded", lookbackMonths: 36 },
      "mutual-of-omaha": { effect: "rated", lookbackMonths: 12 },
    },
  },
  {
    id: "afib",
    name: "Atrial Fibrillation",
    aliases: ["AFib", "A-Fib", "irregular heartbeat", "arrhythmia"],
    category: "cardiac",
    severityWeight: 7,
    carrierImpact: {
      americo: { effect: "preferred_exclusion" },
      corebridge: { effect: "rated" },
      transamerica: { effect: "standard_only", lookbackMonths: 24 },
      aetna: { effect: "non_factor", notes: "Not specifically screened" },
      "american-amicable": { effect: "preferred_exclusion", notes: "Qualifies for immediate benefit" },
      "mutual-of-omaha": { effect: "rated" },
    },
  },
  {
    id: "cardiomyopathy",
    name: "Cardiomyopathy",
    aliases: ["enlarged heart", "heart muscle disease"],
    category: "cardiac",
    severityWeight: 12,
    carrierImpact: {
      americo: { effect: "standard_only", lookbackMonths: 24 },
      corebridge: { effect: "rated" },
      transamerica: { effect: "standard_only", lookbackMonths: 24 },
      aetna: { effect: "modified", lookbackMonths: 12 },
      "american-amicable": { effect: "graded", lookbackMonths: 24 },
      "mutual-of-omaha": { effect: "rated" },
    },
  },
  {
    id: "heart_surgery",
    name: "Heart / Circulatory Surgery",
    aliases: ["bypass surgery", "CABG", "stent", "angioplasty", "pacemaker", "valve replacement", "heart valve"],
    category: "cardiac",
    severityWeight: 11,
    carrierImpact: {
      americo: { effect: "standard_only", lookbackMonths: 24 },
      corebridge: { effect: "rated" },
      transamerica: { effect: "standard_only", lookbackMonths: 24 },
      aetna: { effect: "modified", lookbackMonths: 12 },
      "american-amicable": { effect: "graded", lookbackMonths: 36 },
      "mutual-of-omaha": { effect: "rated" },
    },
  },
  {
    id: "aneurysm",
    name: "Aneurysm",
    aliases: ["aortic aneurysm", "brain aneurysm", "cerebral aneurysm"],
    category: "cardiac",
    severityWeight: 11,
    carrierImpact: {
      americo: { effect: "standard_only", lookbackMonths: 24 },
      corebridge: { effect: "knockout", notes: "Brain aneurysm or recurrent TIA is knockout" },
      transamerica: { effect: "standard_only", lookbackMonths: 24 },
      aetna: { effect: "modified", lookbackMonths: 12 },
      "american-amicable": { effect: "graded", lookbackMonths: 36 },
      "mutual-of-omaha": { effect: "rated" },
    },
  },
  {
    id: "hypertension",
    name: "High Blood Pressure",
    aliases: ["hypertension", "elevated blood pressure", "HBP"],
    category: "cardiac",
    severityWeight: 3,
    carrierImpact: {
      americo: { effect: "non_factor", notes: "Not a knockout; may affect tier on fully UW" },
      corebridge: { effect: "preferred_exclusion", notes: "Controlled may still get preferred" },
      transamerica: { effect: "preferred_exclusion", notes: "Controlled on meds can get preferred" },
      aetna: { effect: "non_factor", notes: "Accepted at preferred level" },
      "american-amicable": { effect: "preferred_exclusion", notes: "Meds in 10 yrs disqualifies from preferred term" },
      "mutual-of-omaha": { effect: "preferred_exclusion" },
    },
  },

  // === CANCER ===
  {
    id: "cancer_active",
    name: "Cancer (Active / Recent)",
    aliases: ["active cancer", "cancer treatment", "chemotherapy", "radiation", "chemo", "tumor", "malignant"],
    category: "cancer",
    severityWeight: 15,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout", lookbackMonths: 24 },
      transamerica: { effect: "knockout", lookbackMonths: 24, notes: "Graded if 2-4 years" },
      aetna: { effect: "knockout", lookbackMonths: 24 },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout", lookbackMonths: 24 },
    },
  },
  {
    id: "cancer_history",
    name: "Cancer (History / Remission)",
    aliases: ["cancer survivor", "cancer remission", "prior cancer", "cancer history"],
    category: "cancer",
    severityWeight: 8,
    carrierImpact: {
      americo: { effect: "standard_only", notes: "Single occurrence, not metastatic" },
      corebridge: { effect: "rated", notes: "Depends on type, stage, time since treatment" },
      transamerica: { effect: "standard_only", lookbackMonths: 48, notes: "Standard if 4+ years" },
      aetna: { effect: "preferred_exclusion", lookbackMonths: 24, notes: "Preferred if 2+ yrs since treatment" },
      "american-amicable": { effect: "graded", lookbackMonths: 36 },
      "mutual-of-omaha": { effect: "rated", notes: "5+ year remission may get standard" },
    },
  },
  {
    id: "cancer_multiple",
    name: "Multiple Cancer Occurrences",
    aliases: ["recurring cancer", "cancer recurrence", "multiple cancers"],
    category: "cancer",
    severityWeight: 15,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout" },
      transamerica: { effect: "knockout" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },
  {
    id: "basal_cell",
    name: "Basal Cell Skin Cancer",
    aliases: ["basal cell carcinoma", "BCC", "squamous cell skin cancer", "non-melanoma skin cancer"],
    category: "cancer",
    severityWeight: 1,
    carrierImpact: {
      americo: { effect: "non_factor" },
      corebridge: { effect: "non_factor" },
      transamerica: { effect: "non_factor" },
      aetna: { effect: "non_factor" },
      "american-amicable": { effect: "non_factor" },
      "mutual-of-omaha": { effect: "non_factor" },
    },
  },

  // === RESPIRATORY ===
  {
    id: "copd",
    name: "COPD",
    aliases: ["chronic obstructive pulmonary disease", "emphysema", "chronic bronchitis"],
    category: "respiratory",
    severityWeight: 9,
    carrierImpact: {
      americo: { effect: "standard_only", notes: "Knockout if requires oxygen" },
      corebridge: { effect: "rated" },
      transamerica: { effect: "standard_only" },
      aetna: { effect: "standard_only" },
      "american-amicable": { effect: "graded", lookbackMonths: 36 },
      "mutual-of-omaha": { effect: "rated", notes: "Knockout if requires oxygen" },
    },
  },
  {
    id: "oxygen_use",
    name: "Supplemental Oxygen Use",
    aliases: ["oxygen therapy", "home oxygen", "O2 dependent"],
    category: "respiratory",
    severityWeight: 15,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout" },
      transamerica: { effect: "knockout" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },
  {
    id: "pulmonary_fibrosis",
    name: "Pulmonary Fibrosis",
    aliases: ["lung fibrosis", "IPF", "idiopathic pulmonary fibrosis"],
    category: "respiratory",
    severityWeight: 14,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout" },
      transamerica: { effect: "knockout" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },
  {
    id: "asthma",
    name: "Asthma",
    aliases: ["chronic asthma", "reactive airway"],
    category: "respiratory",
    severityWeight: 4,
    carrierImpact: {
      americo: { effect: "non_factor", notes: "Mild/moderate not screened" },
      corebridge: { effect: "preferred_exclusion" },
      transamerica: { effect: "standard_only", notes: "Chronic asthma" },
      aetna: { effect: "non_factor" },
      "american-amicable": { effect: "non_factor" },
      "mutual-of-omaha": { effect: "preferred_exclusion" },
    },
  },
  {
    id: "sleep_apnea",
    name: "Sleep Apnea",
    aliases: ["obstructive sleep apnea", "OSA", "CPAP"],
    category: "respiratory",
    severityWeight: 3,
    carrierImpact: {
      americo: { effect: "non_factor" },
      corebridge: { effect: "preferred_exclusion", notes: "Treated/controlled accepted favorably" },
      transamerica: { effect: "preferred_exclusion", notes: "Standard with nightly CPAP" },
      aetna: { effect: "non_factor", notes: "CPAP for sleep apnea excluded from oxygen question" },
      "american-amicable": { effect: "non_factor" },
      "mutual-of-omaha": { effect: "preferred_exclusion", notes: "Standard to Table 2 with CPAP" },
    },
  },

  // === NEUROLOGICAL ===
  {
    id: "alzheimers",
    name: "Alzheimer's Disease",
    aliases: ["Alzheimer's", "Alzheimers", "senile dementia"],
    category: "neurological",
    severityWeight: 15,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout" },
      transamerica: { effect: "knockout" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },
  {
    id: "dementia",
    name: "Dementia",
    aliases: ["cognitive decline", "mental incapacity", "cognitive impairment"],
    category: "neurological",
    severityWeight: 15,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout" },
      transamerica: { effect: "knockout" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },
  {
    id: "als",
    name: "ALS (Lou Gehrig's Disease)",
    aliases: ["amyotrophic lateral sclerosis", "Lou Gehrig's", "motor neuron disease"],
    category: "neurological",
    severityWeight: 15,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout" },
      transamerica: { effect: "knockout" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },
  {
    id: "parkinsons",
    name: "Parkinson's Disease",
    aliases: ["Parkinson's", "Parkinsons"],
    category: "neurological",
    severityWeight: 11,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "graded" },
      transamerica: { effect: "standard_only" },
      aetna: { effect: "standard_only" },
      "american-amicable": { effect: "graded", lookbackMonths: 36 },
      "mutual-of-omaha": { effect: "rated" },
    },
  },
  {
    id: "ms",
    name: "Multiple Sclerosis",
    aliases: ["MS"],
    category: "neurological",
    severityWeight: 11,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "graded" },
      transamerica: { effect: "standard_only" },
      aetna: { effect: "standard_only" },
      "american-amicable": { effect: "graded", lookbackMonths: 36 },
      "mutual-of-omaha": { effect: "rated" },
    },
  },
  {
    id: "huntingtons",
    name: "Huntington's Disease",
    aliases: ["Huntington's", "Huntingtons"],
    category: "neurological",
    severityWeight: 15,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout" },
      transamerica: { effect: "knockout" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },
  {
    id: "seizures",
    name: "Seizure Disorder / Epilepsy",
    aliases: ["epilepsy", "seizures", "convulsions"],
    category: "neurological",
    severityWeight: 7,
    carrierImpact: {
      americo: { effect: "preferred_exclusion" },
      corebridge: { effect: "rated" },
      transamerica: { effect: "standard_only", notes: "12+ seizures in 2 years" },
      aetna: { effect: "non_factor", notes: "Not specifically screened" },
      "american-amicable": { effect: "graded", lookbackMonths: 36 },
      "mutual-of-omaha": { effect: "rated" },
    },
  },

  // === METABOLIC ===
  {
    id: "diabetes_type2",
    name: "Type 2 Diabetes",
    aliases: ["diabetes", "type 2", "adult onset diabetes", "T2D", "high blood sugar"],
    category: "metabolic",
    severityWeight: 6,
    carrierImpact: {
      americo: { effect: "preferred_exclusion", notes: "Complications are knockout" },
      corebridge: { effect: "preferred_exclusion", notes: "Competitive with controlled A1C" },
      transamerica: { effect: "preferred_exclusion" },
      aetna: { effect: "non_factor", notes: "Accepted at preferred if no complications" },
      "american-amicable": { effect: "preferred_exclusion", notes: "Insulin after 50 OK; before 50 = knockout" },
      "mutual-of-omaha": { effect: "preferred_exclusion", notes: "Controlled without complications: standard" },
    },
  },
  {
    id: "diabetes_complications",
    name: "Diabetes with Complications",
    aliases: ["diabetic retinopathy", "diabetic neuropathy", "diabetic nephropathy", "diabetic coma", "insulin shock"],
    category: "metabolic",
    severityWeight: 13,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout", notes: "Diabetic amputation is knockout" },
      transamerica: { effect: "knockout", notes: "Diabetic coma/amputation is knockout" },
      aetna: { effect: "modified", lookbackMonths: 24 },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },

  // === ORGAN DISEASE ===
  {
    id: "kidney_disease",
    name: "Kidney Disease",
    aliases: ["chronic kidney disease", "CKD", "renal disease", "renal failure", "kidney failure"],
    category: "organ_disease",
    severityWeight: 12,
    carrierImpact: {
      americo: { effect: "knockout", notes: "Dialysis is absolute knockout" },
      corebridge: { effect: "graded" },
      transamerica: { effect: "standard_only", lookbackMonths: 48 },
      aetna: { effect: "modified", lookbackMonths: 24 },
      "american-amicable": { effect: "knockout", notes: "Chronic kidney disease/renal insufficiency" },
      "mutual-of-omaha": { effect: "knockout", notes: "Dialysis is knockout" },
    },
  },
  {
    id: "dialysis",
    name: "Kidney Dialysis",
    aliases: ["dialysis", "hemodialysis", "renal dialysis"],
    category: "organ_disease",
    severityWeight: 15,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout" },
      transamerica: { effect: "knockout" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },
  {
    id: "liver_disease",
    name: "Liver Disease / Cirrhosis",
    aliases: ["cirrhosis", "liver failure", "fatty liver", "liver disease"],
    category: "organ_disease",
    severityWeight: 12,
    carrierImpact: {
      americo: { effect: "knockout", notes: "Severe liver disease" },
      corebridge: { effect: "graded" },
      transamerica: { effect: "standard_only", lookbackMonths: 24 },
      aetna: { effect: "modified", lookbackMonths: 24 },
      "american-amicable": { effect: "graded", lookbackMonths: 36 },
      "mutual-of-omaha": { effect: "rated" },
    },
  },
  {
    id: "organ_transplant",
    name: "Organ Transplant",
    aliases: ["transplant", "organ recipient", "kidney transplant", "liver transplant", "heart transplant", "bone marrow transplant"],
    category: "organ_disease",
    severityWeight: 15,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout" },
      transamerica: { effect: "knockout" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },
  {
    id: "hepatitis_c",
    name: "Hepatitis C",
    aliases: ["Hep C", "HCV"],
    category: "organ_disease",
    severityWeight: 10,
    carrierImpact: {
      americo: { effect: "standard_only" },
      corebridge: { effect: "rated" },
      transamerica: { effect: "standard_only", lookbackMonths: 24 },
      aetna: { effect: "non_factor", notes: "Not specifically screened" },
      "american-amicable": { effect: "graded", lookbackMonths: 24 },
      "mutual-of-omaha": { effect: "rated" },
    },
  },

  // === AUTOIMMUNE ===
  {
    id: "lupus",
    name: "Systemic Lupus (SLE)",
    aliases: ["lupus", "SLE", "systemic lupus erythematosus"],
    category: "autoimmune",
    severityWeight: 10,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "graded" },
      transamerica: { effect: "standard_only" },
      aetna: { effect: "standard_only" },
      "american-amicable": { effect: "graded", lookbackMonths: 24 },
      "mutual-of-omaha": { effect: "rated" },
    },
  },

  // === MENTAL HEALTH ===
  {
    id: "depression",
    name: "Depression",
    aliases: ["major depression", "clinical depression", "MDD", "major depressive disorder"],
    category: "mental_health",
    severityWeight: 3,
    carrierImpact: {
      americo: { effect: "non_factor" },
      corebridge: { effect: "preferred_exclusion", notes: "Mild may still get preferred" },
      transamerica: { effect: "preferred_exclusion", notes: "Under 50: standard within 5 years" },
      aetna: { effect: "non_factor", notes: "Accepted at preferred" },
      "american-amicable": { effect: "non_factor", notes: "Qualifies for immediate benefit" },
      "mutual-of-omaha": { effect: "preferred_exclusion", notes: "Controlled with meds: standard" },
    },
  },
  {
    id: "bipolar",
    name: "Bipolar Disorder",
    aliases: ["bipolar", "manic depression", "manic depressive"],
    category: "mental_health",
    severityWeight: 5,
    carrierImpact: {
      americo: { effect: "non_factor" },
      corebridge: { effect: "graded" },
      transamerica: { effect: "standard_only", lookbackMonths: 60, notes: "Under 50" },
      aetna: { effect: "non_factor", notes: "Accepted at preferred" },
      "american-amicable": { effect: "non_factor", notes: "Qualifies for immediate benefit" },
      "mutual-of-omaha": { effect: "preferred_exclusion" },
    },
  },
  {
    id: "schizophrenia",
    name: "Schizophrenia",
    aliases: ["psychosis", "psychotic disorder"],
    category: "mental_health",
    severityWeight: 8,
    carrierImpact: {
      americo: { effect: "non_factor" },
      corebridge: { effect: "knockout", lookbackMonths: 36 },
      transamerica: { effect: "standard_only", lookbackMonths: 60 },
      aetna: { effect: "non_factor", notes: "Accepted at preferred" },
      "american-amicable": { effect: "non_factor", notes: "Qualifies for immediate benefit" },
      "mutual-of-omaha": { effect: "rated" },
    },
  },
  {
    id: "ptsd",
    name: "PTSD",
    aliases: ["post-traumatic stress disorder", "post traumatic stress"],
    category: "mental_health",
    severityWeight: 4,
    carrierImpact: {
      americo: { effect: "non_factor" },
      corebridge: { effect: "preferred_exclusion" },
      transamerica: { effect: "standard_only", lookbackMonths: 60 },
      aetna: { effect: "non_factor" },
      "american-amicable": { effect: "non_factor" },
      "mutual-of-omaha": { effect: "preferred_exclusion" },
    },
  },

  // === SUBSTANCE ABUSE ===
  {
    id: "alcohol_abuse",
    name: "Alcohol Abuse",
    aliases: ["alcoholism", "alcohol dependency", "alcohol addiction", "drinking problem"],
    category: "substance_abuse",
    severityWeight: 9,
    carrierImpact: {
      americo: { effect: "standard_only", lookbackMonths: 24 },
      corebridge: { effect: "rated", lookbackMonths: 24 },
      transamerica: { effect: "standard_only", lookbackMonths: 24 },
      aetna: { effect: "modified", lookbackMonths: 24 },
      "american-amicable": { effect: "graded", lookbackMonths: 36 },
      "mutual-of-omaha": { effect: "rated", lookbackMonths: 24 },
    },
  },
  {
    id: "drug_abuse",
    name: "Drug Abuse",
    aliases: ["substance abuse", "drug addiction", "drug dependency", "illegal drug use", "IV drug use"],
    category: "substance_abuse",
    severityWeight: 12,
    carrierImpact: {
      americo: { effect: "knockout", notes: "Active IV drug use" },
      corebridge: { effect: "rated", lookbackMonths: 24 },
      transamerica: { effect: "standard_only", lookbackMonths: 24, notes: "Illegal use within 1 yr = graded" },
      aetna: { effect: "modified", lookbackMonths: 24 },
      "american-amicable": { effect: "graded", lookbackMonths: 36 },
      "mutual-of-omaha": { effect: "rated", lookbackMonths: 24 },
    },
  },
  {
    id: "dui",
    name: "DUI / DWI",
    aliases: ["driving under influence", "drunk driving", "DUI conviction"],
    category: "substance_abuse",
    severityWeight: 6,
    carrierImpact: {
      americo: { effect: "preferred_exclusion" },
      corebridge: { effect: "rated", lookbackMonths: 24 },
      transamerica: { effect: "preferred_exclusion" },
      aetna: { effect: "modified", lookbackMonths: 24 },
      "american-amicable": { effect: "preferred_exclusion" },
      "mutual-of-omaha": { effect: "rated", notes: "1 DUI 5+ yrs ago may get standard" },
    },
  },

  // === MOBILITY ===
  {
    id: "wheelchair",
    name: "Wheelchair Dependent",
    aliases: ["wheelchair bound", "mobility scooter", "electric scooter", "wheelchair"],
    category: "mobility",
    severityWeight: 14,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout" },
      transamerica: { effect: "knockout" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },
  {
    id: "adl_assistance",
    name: "Needs ADL Assistance",
    aliases: ["activities of daily living", "ADL", "needs help bathing", "needs help dressing", "assisted living"],
    category: "mobility",
    severityWeight: 14,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout" },
      transamerica: { effect: "knockout" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },
  {
    id: "nursing_home",
    name: "Nursing Home / Hospice",
    aliases: ["nursing facility", "skilled nursing", "hospice care", "bedridden", "confined"],
    category: "mobility",
    severityWeight: 15,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout" },
      transamerica: { effect: "knockout" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },

  // === INFECTIOUS ===
  {
    id: "hiv",
    name: "HIV / AIDS",
    aliases: ["HIV positive", "AIDS", "ARC", "human immunodeficiency virus"],
    category: "infectious",
    severityWeight: 15,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout" },
      transamerica: { effect: "knockout" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },

  // === BLOOD ===
  {
    id: "sickle_cell",
    name: "Sickle Cell Anemia",
    aliases: ["sickle cell disease", "sickle cell"],
    category: "blood",
    severityWeight: 13,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout" },
      transamerica: { effect: "knockout" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },

  // === OTHER ===
  {
    id: "amputation_disease",
    name: "Amputation Due to Disease",
    aliases: ["disease amputation", "diabetic amputation", "limb loss from disease"],
    category: "other",
    severityWeight: 14,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout" },
      transamerica: { effect: "knockout" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },
  {
    id: "terminal_illness",
    name: "Terminal Illness",
    aliases: ["terminal", "end stage", "life expectancy under 12 months"],
    category: "other",
    severityWeight: 15,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout" },
      transamerica: { effect: "knockout" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },
  {
    id: "pending_treatment",
    name: "Pending Medical Tests / Surgery",
    aliases: ["awaiting surgery", "pending diagnosis", "scheduled surgery", "pending test results"],
    category: "other",
    severityWeight: 10,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout" },
      transamerica: { effect: "knockout" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },
  {
    id: "cerebral_palsy",
    name: "Cerebral Palsy",
    aliases: ["CP"],
    category: "neurological",
    severityWeight: 12,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "rated" },
      transamerica: { effect: "knockout" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "graded", lookbackMonths: 36 },
      "mutual-of-omaha": { effect: "rated" },
    },
  },
  {
    id: "cystic_fibrosis",
    name: "Cystic Fibrosis",
    aliases: ["CF"],
    category: "respiratory",
    severityWeight: 15,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout" },
      transamerica: { effect: "knockout" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "knockout" },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },
  {
    id: "muscular_dystrophy",
    name: "Muscular Dystrophy",
    aliases: ["MD"],
    category: "neurological",
    severityWeight: 14,
    carrierImpact: {
      americo: { effect: "knockout" },
      corebridge: { effect: "knockout" },
      transamerica: { effect: "knockout" },
      aetna: { effect: "knockout" },
      "american-amicable": { effect: "graded", lookbackMonths: 36 },
      "mutual-of-omaha": { effect: "knockout" },
    },
  },
  {
    id: "high_cholesterol",
    name: "High Cholesterol",
    aliases: ["hyperlipidemia", "elevated cholesterol", "hypercholesterolemia"],
    category: "metabolic",
    severityWeight: 2,
    carrierImpact: {
      americo: { effect: "non_factor" },
      corebridge: { effect: "non_factor", notes: "Controlled may still get preferred" },
      transamerica: { effect: "non_factor", notes: "Controlled may get preferred plus" },
      aetna: { effect: "non_factor" },
      "american-amicable": { effect: "preferred_exclusion", notes: "Meds in 10 yrs disqualifies from preferred term" },
      "mutual-of-omaha": { effect: "non_factor" },
    },
  },
  {
    id: "obesity",
    name: "Obesity",
    aliases: ["overweight", "morbid obesity", "high BMI"],
    category: "metabolic",
    severityWeight: 5,
    carrierImpact: {
      americo: { effect: "preferred_exclusion", notes: "Build chart limits apply" },
      corebridge: { effect: "preferred_exclusion", notes: "BMI up to 31.5 for preferred" },
      transamerica: { effect: "preferred_exclusion" },
      aetna: { effect: "non_factor", notes: "No build chart used" },
      "american-amicable": { effect: "preferred_exclusion", notes: "Liberal build chart" },
      "mutual-of-omaha": { effect: "preferred_exclusion" },
    },
  },
];

// Conditions that NO carrier screens for — always "not a factor"
export const nonFactorConditions: string[] = [
  "chicken pox",
  "varicella",
  "common cold",
  "flu",
  "influenza",
  "seasonal allergies",
  "hay fever",
  "allergic rhinitis",
  "minor sprain",
  "minor fracture",
  "broken bone healed",
  "corrected vision",
  "glasses",
  "contacts",
  "nearsighted",
  "farsighted",
  "mild acne",
  "acne",
  "tonsillectomy",
  "tonsils removed",
  "appendectomy",
  "appendix removed",
  "carpal tunnel",
  "wisdom teeth",
  "dental work",
  "stitches",
  "minor burn",
  "ear infection",
  "strep throat",
  "urinary tract infection",
  "UTI",
  "pink eye",
  "conjunctivitis",
  "sinus infection",
  "sinusitis",
  "cold sore",
  "herpes simplex",
  "plantar wart",
  "ingrown toenail",
  "hemorrhoids",
  "tennis elbow",
  "bunion",
  "lactose intolerance",
  "food allergy",
  "motion sickness",
  "vertigo",
  "migraines",
  "tension headache",
  "acid reflux",
  "GERD",
  "irritable bowel syndrome",
  "IBS",
  "eczema",
  "psoriasis",
  "rosacea",
  "vitamin deficiency",
  "iron deficiency",
  "anemia mild",
];
